version: "3"

services:
  esdm_survey:
    build:
      context: "."
      dockerfile: "deploy/${NODE_ENV:-production}.Dockerfile"
    env_file: ./.env
    ports:
      - ${EXPOSEPORT:-3008}:3000
    volumes:
      - ./:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - esdm-api_sail
networks:
  esdm-api_sail:
    external: true
    driver: bridge
